version: 1
disable_existing_loggers: false

formatters:
  colored:
    (): colorlog.ColoredFormatter
    format: "%(log_color)s%(levelname)-8s%(reset)s %(blue)s%(message)s"
    log_colors:
      DEBUG: "cyan"
      INFO: "green"
      WARNING: "yellow"
      ERROR: "red"
      CRITICAL: "red,bg_white"

handlers:
  console:
    class: logging.StreamHandler
    formatter: colored
    level: DEBUG
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: colored
    filename: logs.log
    level: DEBUG
loggers:
  example:
    level: DEBUG
    handlers: [console, file]
    propagate: no
root:
  level: DEBUG
  handlers: [console, file]